// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWJdE2VHI7RoxXp1hgLxAAdWCqvTQkylA',
    appId: '1:119320217007:web:878c6bc7cc9eaf0a4b1b5a',
    messagingSenderId: '119320217007',
    projectId: 'vegetableorderingsystem',
    authDomain: 'vegetableorderingsystem.firebaseapp.com',
    storageBucket: 'vegetableorderingsystem.firebasestorage.app',
    measurementId: 'G-DF9TB2S53W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTALnlfWlE4LWxHTJm5eniWOtpaUdnq0Y',
    appId: '1:119320217007:android:850fd656b9d7cd094b1b5a',
    messagingSenderId: '119320217007',
    projectId: 'vegetableorderingsystem',
    storageBucket: 'vegetableorderingsystem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRVWUhUiZrznVekA_l9PsDeCpeU6V22iA',
    appId: '1:119320217007:ios:777f4113c282a8564b1b5a',
    messagingSenderId: '119320217007',
    projectId: 'vegetableorderingsystem',
    storageBucket: 'vegetableorderingsystem.firebasestorage.app',
    iosBundleId: 'com.example.vegetableOrderingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRVWUhUiZrznVekA_l9PsDeCpeU6V22iA',
    appId: '1:119320217007:ios:777f4113c282a8564b1b5a',
    messagingSenderId: '119320217007',
    projectId: 'vegetableorderingsystem',
    storageBucket: 'vegetableorderingsystem.firebasestorage.app',
    iosBundleId: 'com.example.vegetableOrderingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWJdE2VHI7RoxXp1hgLxAAdWCqvTQkylA',
    appId: '1:119320217007:web:49f88521e445ea8a4b1b5a',
    messagingSenderId: '119320217007',
    projectId: 'vegetableorderingsystem',
    authDomain: 'vegetableorderingsystem.firebaseapp.com',
    storageBucket: 'vegetableorderingsystem.firebasestorage.app',
    measurementId: 'G-R9LPMVCDL4',
  );
}
